### ISSUE TITLE
Overloading `chiamata (f)` dell'esercizio #1 esame 20120202

### ISSUE THREAD

**Issue by MarkGotLasagna** [merendamattia/MdP#45]
Seguendo la logica di Overloading, per la seguente linea le funzioni utilizzabili dovrebbero coincidere con le funzioni candidate. Questo è dedotto dalla [Fase 2: selezione delle funzioni utilizzabili](https://github.com/merendamattia/MdP/blob/main/teoria/12-overloading.md#fase-2-selezione-delle-funzioni-utilizzabili).

https://github.com/merendamattia/MdP/blob/683e5a14733c583eaa798e612422bac506ed7750/vecchi_esami/20120202/%40manueldiagostino/esercizio_1.cpp#L32

Intellisense lo accenna.

![image](https://github.com/merendamattia/MdP/assets/59115463/0cc0428d-f820-4cc5-910a-6881501477c9)

Può essere confermato?

**Comment by merendamattia** [comment]
Sì, in questo caso le utilizzabili sarebbero tutte e tre {1,2,5}. 
Come migliore viene scelta la {2} perchè i parametri sono delle corrispondenze esatte.
